language: php

sudo: false

php:
  - 5.3

before_script:
  - "mkdir fluxbb && cd fluxbb"
  - "git clone --quiet git://github.com/fluxbb/fluxbb.git ."
  - "git checkout fluxbb-1.4"
  - "cd .. && mkdir sql-dumps && cd sql-dumps"
  - "git clone --quiet git://github.com/daris/sql-dumps.git ."
  - for i in *.sql; do db_name=`echo $i| sed 's/.sql//g'`; echo Importing $db_name; mysql -e "create database $db_name"; mysql $db_name < $db_name.sql ; done
  - echo Importing merge__fluxbb; mysql -e "create database merge__fluxbb"; mysql merge__fluxbb < fluxbb__test.sql
  - "cd .."
  - "cp tests/config.php fluxbb/config.php"
  - "php fluxbb/index.php > index.txt" # Generate fluxbb cache
#  - "psql -c 'create database fluxbb__test;' -U postgres"

script: "cd tests && phpunit --bootstrap bootstrap.php ConverterTest.php"

notifications:
  email:
    recipients:
      - daris91@gmail.com
    on_success: never
    on_failure: always
